### ISSUE TITLE
Use Kubernetes Cluster API Provider OpenStack

### ISSUE THREAD

**Issue by berendt** [23technologies/testbed-gardener#16]
The creation of the cluster for Gardener should not be done by Terraform. Use the Kubernetes Cluster API Provider OpenStack for it.

Re-use https://github.com/SovereignCloudStack/k8s-cluster-api-provider for it.

**Comment by berendt** [comment]
Discussion on Tuesday at the refinement meeting.

**Comment by fynluk** [comment]
closed by #88
