### ISSUE TITLE
replace storageclasse gardener.fast with cinder-default

### ISSUE THREAD

**Issue by mxmxchere** [23technologies/testbed-gardener#2]
Gardener creates etcd-instances with a pvc with a storageclass that is not working. If it is changed to cinder-default or something different that is available it works.

**Comment by berendt** [comment]
You removed the storage class configuration with a6e9bcd2a53fe72eff4422fb9c2dbcdb95e5bd23. Something like this should work?

```
-#      provider-openstack:
-#        valueOverwrites:
-#          config:
-#            etcd:
-#             storage:
-#               className: gardener.cloud-fast
-#               capacity: 1Gi
-#               provisioner: kubernetes.io/no-provisioner
```

**Comment by mxmxchere** [comment]
i'll give it a try

**Comment by mxmxchere** [comment]
i have experimented with these options but haven't found one that works yet. i will continue to try things when i have a running instance again
