### ISSUE TITLE
Delete all generated Key-Pairs while make purge

### ISSUE THREAD

**Issue by fynluk** [23technologies/testbed-gardener#32]

**Comment by mxmxchere** [comment]
I guess we have to reopen this one. it seems that ssh-keypairs are shared among projects. so if there are two deployments on one domain this purge will accidently remove foreign keys

**Comment by mxmxchere** [comment]
My suggested solution:

1. suffix the key with the project name
2.  delete only this key when purging
3. make a new make-target "purge all keys" with a seperate warning that this will purge all keys from all projects.

**Comment by mxmxchere** [comment]
don't forget to template the cloud (currently its gx-bc)
